[package]
name = "fin"
version = "0.1.0"
authors = ["Mitchel <mwassler@covermymeds.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "2.26.0", features = ["yaml"]}
currency = "0.4.0"

